version: "3.3"
services:
  nextjs:
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/movable/app
      - /var/movable/app/node_modules
      - /var/movable/app/.next
