---
- name: Create pods using deployment
  hosts: kubernetes
  become: false
  user: admin

  tasks:
    - name: create a deployment
      command: kubectl apply -f k8s/client-deployment.yml

    - name: update deployment with new pods if image updated in amazon ecr
      command: kubectl rollout restart deployment.v1.apps/client-deployment
